name: 💡 Feature Request
description: Suggest an improvement you’d like to see
title: "[feat]: "
labels: [ "⏫ enhancement", "enhancement" ]
assignees: [ trueberryless ]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this feature request! 🚀
  - type: textarea
    id: summary
    attributes:
      label: What is your idea?
      description: A brief, one or two sentence description of your idea for a new feature.
    validations:
      required: true
  - type: textarea
    id: background
    attributes:
      label: Why is this feature necessary?
      description: Explain why this feature is important. What problems would it solve? Which users would it help?
    validations:
      required: true
  - type: textarea
    id: prior-art
    attributes:
      label: Do you have examples of this feature in other projects?
      description: Help us understand your idea by sharing links to example implementations we can compare against.
      placeholder: |
        - Example
        - Example
        - Example
  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
  - type: checkboxes
    id: will-pr
    attributes:
      label: Participation
      options:
        - label: I am willing to submit a pull request for this feature.
          required: false
